DROP PROCEDURE IF EXISTS RECORD_HISTORY;
DELIMITER $$
CREATE PROCEDURE RECORD_HISTORY(IN NEWDATE DATE)
BEGIN 
INSERT INTO HISTORY SELECT * FROM RESERVATION WHERE DATE < NEWDATE;
DELETE FROM RESERVATION WHERE DATE < NEWDATE;
END $$
DELIMITER ;

DROP PROCEDURE IF EXISTS RESERVATION_FROM_SCHEDULE;
DELIMITER $$
CREATE PROCEDURE RESERVATION_FROM_SCHEDULE()
BEGIN 
WHILE SELECT * FROM SCHEDULE WHERE REFLECTED = 'X' IS NOT NULL DO

END WHILE;
INSERT INTO RESERVATION SELECT * FROM RESERVATION WHERE DATE < NEWDATE;
DELETE FROM RESERVATION WHERE DATE < NEWDATE;
END $$
DELIMITER ;


CALL RECORD_HISTORY(20140101);
create index Index_history_1 on history(DATE);

